# 📝 NumPy Assignment

This assignment covers basics of NumPy arrays, array creation, arithmetic operations, and aggregations.

## 📌 Section 1: Creating Arrays

### Q1. Create a **1D NumPy array** of integers from 10 to 19 (inclusive).

### Q2. Create a **2D NumPy array** of shape (3, 4) with all elements as float `7.5`.

### Q3. Create a **3D NumPy array** of shape (2, 3, 4) filled with random integers between 0 and 9.

### Q4. Create a **6D NumPy array** with shape `(1,2,1,2,1,2)` filled with zeros.

## 📌 Section 2: Array Creation Functions

### Q5. Use `np.zeros` and `np.reshape` to create a **4x3 matrix** of zeros.

### Q6. Use `np.arange` and `np.reshape` to create a **3x3 matrix** of numbers from 1 to 9.

### Q7. Create a **1D array of 5 ones** with data type `int32`.

### Q8. Combine `np.arange` and `np.reshape` to create a **3D array** of shape `(2,2,3)` containing numbers from 1 to 12.

## 📌 Section 3: Arithmetic Operations

### Q9. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`. Perform **addition, subtraction, multiplication, and division**.

### Q10. Multiply every element of the array `[2, 4, 6, 8]` by `3`.

## 📌 Section 4: Aggregation Functions

### Q11. Given an array `x = np.array([5, 10, 15, 20, 25])`, find the **sum, mean, max, and min**.

### Q12. Create a **3x3 matrix** with values from 1 to 9 and find the **row-wise sum and column-wise mean**.

## 📌 Section 5: For Loop Practice

### Q13. Use a **for loop** to create a list of squares of numbers from 1 to 10.

### Q14. Use a **for loop** to create a DataFrame with two columns:

* `Number` → values from 1 to 5
* `Square` → square of each number

## 📌 Section 6: Looping Forward and Backward Through Columns

### Q15. Loop **forward** through the columns `["A", "B", "C"]`, assign values `1, 2, 3` respectively, and create a DataFrame with 1 row.

### Q16. Loop **forward** through numbers 1 to 5, create columns `Col1` to `Col5`, and assign each column its square values for rows 1 to 5.

### Q17. Loop **backward** through the columns `["X", "Y", "Z"]`, assign values `10, 20, 30` respectively, and create a DataFrame with 1 row.

### Q18. Loop **backward** through numbers 1 to 4, create columns `C4, C3, C2, C1`, and assign each column values `[1,2,3,4]`.

## 📌 Section 8: Word Problems Using Loops

### Q21. SUM OF ALL EVEN NUMBERS FROM 1 TO 50  
Write a Python program to calculate the **sum of all even numbers** from 1 to 50 using a `for` loop.

### Q22. PRINT MULTIPLICATION TABLE OF 7

Write a Python program to **print the multiplication table of 7** from 1 to 10 using a `for` loop.

### Q23. CALCULATE FACTORIAL OF A NUMBER

Write a Python program to calculate the **factorial of 6** using a `for` loop.

### Q24. COUNT OCCURRENCES OF EACH CHARACTER IN A STRING

Given the string `"python loops"`, write a Python program to **count the occurrence of each character** using a `for` loop.

## 📌 Section 9: Intermediate Computation Using Loops

### Q25. FOR LOOP: CALCULATE FIBONACCI SERIES UP TO N TERMS  
Write a Python program to generate the **first 10 terms of the Fibonacci series** using a `for` loop.

### Q26. WHILE LOOP: SUM OF DIGITS OF A NUMBER

Write a Python program to calculate the **sum of digits of 58742** using a `while` loop.

## 📌 Section 10: Do-While and Do-Until Simulation

- Python doesn’t have built-in `do-while` or `do-until`, but we can simulate them using `while True` with a break condition.

### Q27. SIMULATE DO-WHILE LOOP: counting until a condition

### Q28. SIMULATE DO-UNTIL LOOP: COUNTDOWN FROM 5 TO 1

Write a Python program to **print numbers from 5 down to 1** using a `do-until` style loop (execute loop at least once and stop when number < 1).

✅ Explanation:  
- **Do-while:** Executes the block at least once and repeats while the condition is true.  
- **Do-until:** Executes the block at least once and repeats until the condition becomes true.

## 📌 Section 11: Special Statements – break, exit, pass

### Q29. USING `break`: FIND FIRST NUMBER DIVISIBLE BY 7 IN A LIST  
Write a Python program to **find the first number divisible by 7** in the list `[10, 13, 20, 28, 35]` using a `for` loop and `break`.

### Q30. USING `exit()`: TERMINATE PROGRAM WHEN A NEGATIVE NUMBER IS FOUND IN A LIST  
Write a Python program to **scan the list `[5, 8, 12, -3, 7]`** and terminate the program immediately using `exit()` if a negative number is found.  

- uncomment this and run.

In [28]:
# import sys

# numbers = [5, 8, 12, -3, 7]

# for n in numbers:
#     if n < 0:
#         sys.exit(f"Negative number {n} found. Program terminated.")
#     print(f"Number: {n}")

### Q31. USING `pass`: SKIP SPECIFIC CONDITION IN LOOP

Write a Python program to **print numbers from 1 to 5** but **skip 3** using `pass`.



## 📌 Section 12: Nested Loops

### Q32. NESTED FOR LOOPS: PRINT A PATTERN  
Write a Python program to **print the following pattern** using nested `for` loops:  

```

```
*
* *
* * *
* * * *
* * * * *
```

### Q33. COMBINED FOR AND WHILE LOOPS: MULTIPLICATION TABLE OF 1 TO 3

Write a Python program using a **for loop** for numbers 1 to 3 and a **while loop** to print their multiplication table up to 5.

## 📌 Section 13: Broadcasted Addition

### Q34. ADD A 1D ARRAY TO EACH ROW OF A 2D ARRAY  
Given a 2D array:

Use **broadcasting** to add `arr_1d` to each row of `arr_2d`.

### Q35. ADD A COLUMN VECTOR TO EACH COLUMN OF A 2D ARRAY

Given a 2D array:

Use **broadcasting** to add `col_vec` to each column of `arr_2d`.

## 📌 Section 14: Linear Algebra (Matrix Operations)

### Q36. MATRIX MULTIPLICATION

Given matrices:

Compute the **matrix multiplication** $A \times B$.

### Q37. DETERMINANT AND INVERSE OF A MATRIX

Given matrix:

Calculate the **determinant** and **inverse** of `M`.

## 📌 Section 15: Numerical Maniputlations

In [ ]:
import pandas as pd
from io import StringIO

# Create a CSV-like string with ':' delimiter and extra numeric columns
data = """NAME:GENDER:EDUCATION:SAS:R:PYTHON:SQL:EXCEL:AGE:YEARLY_SALARY
PREETAM:MALE:MBA:800::600:700:650:30:75000
RAJ:FEMALE:BTECH:700:800:500:400:300:28:68000
LAVLIN:MALE:BTECH:100:200::300:250:25:50000
ANITA:FEMALE:MCA::650:700:600:0:27:72000
KUMAR:MALE:MSC:500:550:600:450:400:32:80000
PRIYA:FEMALE:BTECH:600:700:750:500:450:26:70000
VIKRAM:MALE:MBA:750:800:700:650:600:31:78000
SUNITA:FEMALE:MCA:500:600:550:400:350:29:69000
RAHUL:MALE:BTECH:450:500:400:350:300:27:65000
MEERA:FEMALE:MSC:600:650:700:550:500:30:73000
"""

# Use StringIO to simulate reading from a file
df = pd.read_csv(StringIO(data), delimiter=':')

Modified DataFrame:
      NAME  GENDER EDUCATION    SAS      R  PYTHON  SQL  EXCEL  AGE  \
0  PREETAM    MALE       MBA  800.0    0.0   600.0  700    650   30
1      RAJ  FEMALE     BTECH  700.0  800.0   500.0  400    300   28
2   LAVLIN    MALE     BTECH  100.0  200.0     0.0  300    250   25
3    ANITA  FEMALE       MCA    0.0  650.0   700.0  600      0   27
4    KUMAR    MALE       MSC  500.0  550.0   600.0  450    400   32
5    PRIYA  FEMALE     BTECH  600.0  700.0   750.0  500    450   26
6   VIKRAM    MALE       MBA  750.0  800.0   700.0  650    600   31
7   SUNITA  FEMALE       MCA  500.0  600.0   550.0  400    350   29
8    RAHUL    MALE     BTECH  450.0  500.0   400.0  350    300   27
9    MEERA  FEMALE       MSC  600.0  650.0   700.0  550    500   30

   YEARLY_SALARY
0          75000
1          68000
2          50000
3          72000
4          80000
5          70000
6          78000
7          69000
8          65000
9          73000

In [1]:

# Replace missing values

In [2]:
# Convert appropriate columns to numeric

In [3]:


# Print the modified DataFrame

### Questions & Answers:

#### Q1. Compute the **average score** for each student across SAS, R, PYTHON, SQL, and EXCEL.

#### Q2. Find the **maximum and minimum yearly salary** among all employees.

#### Q3. Create a new column **TOTAL\_SCORE** as the sum of all skills.

#### Q4. Find the **name(s) of student(s) having TOTAL\_SCORE greater than 3000**.

#### Q5. Calculate the **average age of employees who scored more than 600 in PYTHON**.

#### Q6. Replace any **0 values in numeric columns with the column mean**.

#### Q7. Sort the DataFrame based on **YEARLY\_SALARY in descending order**.

Yes! You **can use `melt` + `groupby`**, but it’s **a bit more roundabout** than just using `mean(axis=1)` for row-wise averages. It’s usually useful if you want to **reshape the data to long format**, maybe for plotting or grouped aggregations. Let me show you how.

#### Q8. Compute the **average score** for each student across SAS, R, PYTHON, SQL, and EXCEL.

- **Method - 1**

- **Method - 2: Using Melt()**

### **Step 1: Melt the DataFrame**

We convert the score columns into a long format:

In [50]:
score_cols = ['SAS','R','PYTHON','SQL','EXCEL']

df_melted = df.melt(id_vars=['NAME'], value_vars=score_cols,
                    var_name='SUBJECT', value_name='SCORE')

df_melted.head()

      NAME SUBJECT       SCORE
0  PREETAM     SAS  800.000000
1      RAJ     SAS  700.000000
2   LAVLIN     SAS  100.000000
3    ANITA     SAS  555.555556
4    KUMAR     SAS  500.000000

**Output (example):**

```
     NAME  SUBJECT  SCORE
0  PREETAM     SAS    800
1      RAJ     SAS    700
2    LAVLIN     SAS    100
3    ANITA     SAS      0
4    KUMAR     SAS    500
...
```

### **Step 2: Group by NAME and compute average**

Now, we can use `groupby` to calculate the average per student:

In [51]:
average_scores = df_melted.groupby('NAME')['SCORE'].mean().reset_index()
average_scores.rename(columns={'SCORE':'AVERAGE_SCORE'}, inplace=True)

average_scores

      NAME  AVERAGE_SCORE
0    ANITA     585.555556
1    KUMAR     500.000000
2   LAVLIN     292.222222
3    MEERA     600.000000
4  PREETAM     671.111111
5    PRIYA     600.000000
6    RAHUL     400.000000
7      RAJ     540.000000
8   SUNITA     480.000000
9   VIKRAM     700.000000

**Output:**

```
      NAME  AVERAGE_SCORE
0    ANITA          530.0
1    KUMAR          500.0
2    LAVLIN         170.0
3    MEERA          630.0
4    PREETAM        550.0
5    PRIYA          600.0
6    RAJ            540.0
7    RAHUL          400.0
8    SUNITA         480.0
9    VIKRAM         700.0
```

✅ This gives the **same result as `mean(axis=1)`**, but uses `melt` + `groupby`.

### **Step 3 (Optional): Merge back to original DataFrame**

If you want the `AVERAGE_SCORE` column in the original DataFrame:

In [52]:
df = df.merge(average_scores, on='NAME')
# df[['NAME','AVERAGE_SCORE']]

💡 **Key notes:**

* `melt` is useful for **long-format data** or **grouped aggregations**.
* For simple **row-wise averages**, `df[cols].mean(axis=1)` is more direct.
* `groupby` is more natural for **column-wise aggregation by groups**, e.g., `CLASS` or `GENDER`.

#### Q9: compute **average scores per group** using `melt` + `groupby`. Here’s how:

### **Step 1: Melt the DataFrame (scores only)**

In [53]:
score_cols = ['SAS','R','PYTHON','SQL','EXCEL']

df_melted = df.melt(id_vars=['NAME','GENDER','EDUCATION'], 
                    value_vars=score_cols,
                    var_name='SUBJECT', value_name='SCORE')

df_melted.head()

      NAME  GENDER EDUCATION SUBJECT       SCORE
0  PREETAM    MALE       MBA     SAS  800.000000
1      RAJ  FEMALE     BTECH     SAS  700.000000
2   LAVLIN    MALE     BTECH     SAS  100.000000
3    ANITA  FEMALE       MCA     SAS  555.555556
4    KUMAR    MALE       MSC     SAS  500.000000

**Output example:**

```
     NAME  GENDER EDUCATION  SUBJECT  SCORE
0  PREETAM    MALE       MBA      SAS    800
1      RAJ  FEMALE     BTECH      SAS    700
2    LAVLIN    MALE     BTECH      SAS    100
3    ANITA  FEMALE       MCA      SAS      0
4    KUMAR    MALE      MSC      SAS    500
```

### **Step 2: Group by GENDER (or EDUCATION) and compute average score**

In [54]:
# Average score per GENDER
gender_avg = df_melted.groupby('GENDER')['SCORE'].mean().reset_index()
gender_avg.rename(columns={'SCORE':'AVERAGE_SCORE'}, inplace=True)

print(gender_avg)

   GENDER  AVERAGE_SCORE
0  FEMALE     561.111111
1    MALE     512.666667

**Output:**

```
   GENDER  AVERAGE_SCORE
0  FEMALE     532.5
1    MALE     512.0
```

In [55]:
# Average score per EDUCATION
education_avg = df_melted.groupby('EDUCATION')['SCORE'].mean().reset_index()
education_avg.rename(columns={'SCORE':'AVERAGE_SCORE'}, inplace=True)

print(education_avg)

  EDUCATION  AVERAGE_SCORE
0     BTECH     458.055556
1       MBA     685.555556
2       MCA     532.777778
3       MSC     550.000000

**Output:**

```
  EDUCATION  AVERAGE_SCORE
0      BTECH     430.0
1        MBA     650.0
2        MCA     462.5
3        MSC     562.5
```

### **Step 3 (Optional): Merge back to original DataFrame**

If you want to **add group-level averages** back to the original DataFrame:

In [56]:
df = df.merge(gender_avg, on='GENDER', suffixes=('', '_GENDER'))
df = df.merge(education_avg, on='EDUCATION', suffixes=('', '_EDU'))

df[['NAME','GENDER','AVERAGE_SCORE','AVERAGE_SCORE_EDU']]

      NAME  GENDER  AVERAGE_SCORE  AVERAGE_SCORE_EDU
0  PREETAM    MALE     512.666667         685.555556
1      RAJ  FEMALE     561.111111         458.055556
2   LAVLIN    MALE     512.666667         458.055556
3    ANITA  FEMALE     561.111111         532.777778
4    KUMAR    MALE     512.666667         550.000000
5    PRIYA  FEMALE     561.111111         458.055556
6   VIKRAM    MALE     512.666667         685.555556
7   SUNITA  FEMALE     561.111111         532.777778
8    RAHUL    MALE     512.666667         458.055556
9    MEERA  FEMALE     561.111111         550.000000

**Now you have:**

* Individual row scores (if you want)
* Average score per gender (`AVERAGE_SCORE`)
* Average score per education (`AVERAGE_SCORE_EDU`)

✅ **Summary:**

1. `melt` transforms wide score columns into long format.
2. `groupby` + `mean()` computes average per group.
3. `merge` can attach the group averages back to the original DataFrame.

#### Q10:  Use **`groupby().transform()`**, to calculate **group-level averages** **directly** without melting or merging. 

- `transform` returns a Series aligned with the original DataFrame, so it can be assigned as a new column.

### **1️⃣ Row-wise average (per student)**

In [57]:
score_cols = ['SAS','R','PYTHON','SQL','EXCEL']

# Average score per row
df['AVERAGE_SCORE'] = df[score_cols].mean(axis=1)
df[['NAME','AVERAGE_SCORE']]

      NAME  AVERAGE_SCORE
0  PREETAM     671.111111
1      RAJ     540.000000
2   LAVLIN     292.222222
3    ANITA     585.555556
4    KUMAR     500.000000
5    PRIYA     600.000000
6   VIKRAM     700.000000
7   SUNITA     480.000000
8    RAHUL     400.000000
9    MEERA     600.000000

✅ Same as before, simple row-wise mean.

### **2️⃣ Average score per GENDER using transform**

In [58]:
# Compute average of all score columns per gender
df['GENDER_AVG'] = df[score_cols].mean(axis=1)  # start with row-wise sum
df['GENDER_AVG'] = df.groupby('GENDER')[score_cols].transform('mean').mean(axis=1)

df[['NAME','GENDER','GENDER_AVG']]

      NAME  GENDER  GENDER_AVG
0  PREETAM    MALE  512.666667
1      RAJ  FEMALE  561.111111
2   LAVLIN    MALE  512.666667
3    ANITA  FEMALE  561.111111
4    KUMAR    MALE  512.666667
5    PRIYA  FEMALE  561.111111
6   VIKRAM    MALE  512.666667
7   SUNITA  FEMALE  561.111111
8    RAHUL    MALE  512.666667
9    MEERA  FEMALE  561.111111

**Explanation:**

1. `df.groupby('GENDER')[score_cols]` → select numeric columns per group.
2. `.transform('mean')` → compute **mean per column within the group**, returned as a DataFrame aligned with `df`.
3. `.mean(axis=1)` → average across the score columns per student to get **group average**.

### **3️⃣ Average score per EDUCATION using transform**

In [59]:
df['EDU_AVG'] = df.groupby('EDUCATION')[score_cols].transform('mean').mean(axis=1)
df[['NAME','EDUCATION','EDU_AVG']]

      NAME EDUCATION     EDU_AVG
0  PREETAM       MBA  685.555556
1      RAJ     BTECH  458.055556
2   LAVLIN     BTECH  458.055556
3    ANITA       MCA  532.777778
4    KUMAR       MSC  550.000000
5    PRIYA     BTECH  458.055556
6   VIKRAM       MBA  685.555556
7   SUNITA       MCA  532.777778
8    RAHUL     BTECH  458.055556
9    MEERA       MSC  550.000000

### ✅ **Advantages of using transform**

* No need to `melt` or `merge`.
* Returns a **Series aligned with original DataFrame**.
* Works nicely for **row-level + group-level computations**.

# 📝 Visualization Assignment: Bar Plot

In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Create a sample DataFrame with 25 rows
np.random.seed(42)

data = {
    "STATE_CODE": [f"S{i:02d}" for i in range(1, 26)],  # 25 states
    "SUBS": np.random.randint(100, 1000, 25),  # Subscribers count
    "USERS": np.random.randint(50, 500, 25),   # Active users
    "REVENUE": np.random.randint(10000, 50000, 25),  # Revenue in dollars
    "GROWTH_%": np.random.uniform(1, 15, 25).round(2)  # Growth rate %
}

med_summary = pd.DataFrame(data)

print(med_summary.head())

  STATE_CODE  SUBS  USERS  REVENUE  GROWTH_%
0        S01   202    463    41551      8.95
1        S02   535    343    21394      1.44
2        S03   960    435    13556     12.79
3        S04   370    241    13890      7.30
4        S05   206    493    40740      6.53

### ❓ Question:

**Plot a bar chart of STATE\_CODE vs REVENUE to analyze which states are generating the highest revenue.**

### ✅ Answer with Code:

# 📝 Visualization Assignment: Pie Chart

### Question:

Create a pie chart to visualize the percentage distribution of subscribers across states from the `med_summary` DataFrame.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# Sample dataset
data = {
    'STATE_CODE': ['AP', 'TN', 'KA', 'MH', 'DL', 'GJ', 'RJ', 'WB'],
    'SUBS': [1200, 1500, 1100, 1800, 900, 1300, 800, 1600]
}

med_summary = pd.DataFrame(data)

# 📝 Visualization Assignment: Pie Chart with Explode

In [2]:
import pandas as pd
from matplotlib import pyplot as plt

# Step 1: Create a DataFrame
data = {'Player': ['Smith', 'Finch', 'Warner', 'Lumberchane'],
        'Runs': [42, 32, 18, 24]}

df = pd.DataFrame(data)

# 📝 Visualization Assignment: Line Chart

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Create a NEW dataset (Monthly Sales Example)
data = {
    'MONTH': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
    'SALES': [1200, 1500, 1700, 1600, 1800, 2200, 2100, 2500]
}

sales_summary = pd.DataFrame(data)

# 📝 Visualization Assignment: Dynamic Bar Chart

In [5]:
import matplotlib.pyplot as plt
import pandas as pd

# New dataset: Sales in regions
sales = [25, 40, 15, 30, 55]
regions = ('North', 'South', 'East', 'West', 'Central')

df = pd.DataFrame({'sales': sales,
                   'regions': regions})

# 📝 Assignment: Radar Chart with Custom Parameters

### Dataset & Code

In [6]:
# Libraries
import matplotlib.pyplot as plt
import pandas as pd
from math import pi

# New dataset
df = pd.DataFrame({
    'group': ['X','Y','Z','W'],
    'speed': [25, 35, 15, 30],
    'accuracy': [40, 20, 35, 25],
    'strength': [30, 10, 25, 40],
    'stamina': [15, 35, 20, 30],
    'strategy': [20, 40, 25, 15]
})

### ❓ Questions

1. What does `ax.set_theta_offset(pi / 2)` do?

   * (a) Starts first axis at the top
   * (b) Rotates chart by 180°
   * (c) Removes axis labels
   * (d) Sets axis spacing

2. What happens if we change `ax.set_theta_direction(-1)` to `1`?

   * (a) Plot is drawn clockwise
   * (b) Plot is drawn counter-clockwise
   * (c) Nothing changes
   * (d) Y-axis labels disappear

3. Why do we set `plt.ylim(0,50)` even though data max is 40?

   * (a) To hide outliers
   * (b) To add padding space in chart
   * (c) To normalize values
   * (d) To shift labels

Here’s the **Visualization Assignment** version for your **Donut Chart** example, with questions on parameters and full code included:

# 📝 Visualization Assignment: Donut Chart

### Questions:

1. What is the use of the parameter `plt.Circle((0,0), 0.7, color='white')` in this chart?
2. How does changing the radius (e.g., `0.7`) affect the appearance of the donut hole?
3. Which parameter of `plt.pie()` can be used to show percentage values inside the chart?
4. What is the purpose of `plt.gcf().gca().add_artist(my_circle)` in this code?

In [7]:
# Libraries
import matplotlib.pyplot as plt

# Create data
size_of_groups = [12, 11, 3, 30]

Got it 👍 I’ll create a **new dataset**, update the **stacked bar chart code**, and then write **assignment questions + answers in your format**.

Here’s the full code + Q\&A:

In [8]:
# 📊 Visualization with Stacked Bar Chart

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Define categories and values for each bar segment
departments = ['HR', 'Finance', 'IT', 'Marketing']

salaries = [40, 55, 60, 35]   # Base salary component
bonuses = [10, 15, 12, 8]     # Bonus component
benefits = [5, 10, 7, 6]      # Benefits component

# 📝 Assignment: Stacked Bar Chart

### **Q1.**

Plot the stacked bar chart for the given data of **departments** with `salaries`, `bonuses`, and `benefits`.
Which department has the **highest total compensation**?

✅ **Answer:**

* HR → 40 + 10 + 5 = **55**
* Finance → 55 + 15 + 10 = **80**
* IT → 60 + 12 + 7 = **79**
* Marketing → 35 + 8 + 6 = **49**

👉 **Finance has the highest total compensation (80).**

### **Q2.**

Modify the chart to **exclude bonuses** and only plot **salaries + benefits**. Which department now has the **lowest compensation**?

✅ **Answer:**

* HR → 40 + 5 = **45**
* Finance → 55 + 10 = **65**
* IT → 60 + 7 = **67**
* Marketing → 35 + 6 = **41**

👉 **Marketing has the lowest compensation (41).**

Here’s a **fresh dataset** with the same **scatterplot assignment** format, including both **Matplotlib** and **Seaborn** plots, along with **assignment question + solution** in your style:

# 📝 Assignment: Scatter Plot Visualization

### **Q1.**

Create a scatter plot using **Matplotlib** and **Seaborn** for the following dataset. Use different colors for categories in Seaborn.

In [69]:
# Step 1: Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Create a NEW dataset
data = {
    'X': [10, 15, 8, 20, 5, 18, 12, 25, 7, 14],
    'Y': [50, 60, 45, 70, 40, 65, 55, 80, 42, 58],
    'Category': ['Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue']
}

df = pd.DataFrame(data)

# 📝 Assignment: Bubble Chart Visualization

### **Q1.**

Create a bubble chart using Matplotlib for the given dataset. Use `X` for x-axis, `Y` for y-axis, and `Size` for bubble sizes. Include a legend showing the bubble size scale.

In [10]:
# Step 1: Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Create a NEW dataset
data = {
    'X': [10, 15, 12, 20, 8, 25, 18, 30, 22, 16],  # X-axis values
    'Y': [60, 75, 70, 85, 55, 90, 80, 95, 78, 72], # Y-axis values
    'Size': [150, 250, 200, 300, 180, 350, 280, 400, 220, 260],  # Bubble sizes
    'Category': ['Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue']
}

# Convert to DataFrame
df = pd.DataFrame(data)

Here’s a **new dataset** and a **complete assignment version** for your **histogram example**, including **Matplotlib and Seaborn**, with explanation in your format:

# 📝 Assignment: Histogram Visualization

### **Q1.**

Create a histogram to visualize the distribution of the dataset using **Matplotlib** and **Seaborn**. Use appropriate bins and colors, and add a **KDE curve** in Seaborn.

In [73]:
# Step 1: Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Create a NEW dataset
data = {
    'Values': [15, 20, 25, 18, 30, 22, 40, 35, 28, 32, 45, 38, 50, 42, 60, 55, 48, 70, 65, 58]
}

df = pd.DataFrame(data)

# 📝 Assignment: Box Plot Visualization

### **Q1.**

Create a box plot using **Matplotlib** to visualize the distribution of values for each category in the dataset. Customize the box color and add grid lines for clarity.

In [76]:
# Step 1: Import libraries
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Create a NEW dataset
data = {
    'Category': ['X', 'X', 'X', 'X', 'X', 
                 'Y', 'Y', 'Y', 'Y', 'Y', 
                 'Z', 'Z', 'Z', 'Z', 'Z'],
    'Values': [12, 15, 14, 13, 16, 
               22, 25, 23, 21, 24, 
               35, 38, 36, 37, 34]
}

df = pd.DataFrame(data)

# 📝 Assignment: Line Chart Visualization

### **Q1.**

Create a line chart to compare two variables over time using both **Matplotlib** and **Seaborn**. Include markers at each point, rotate x-axis labels for better readability, and add a legend.

In [11]:
# Step 1: Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Create a NEW dataset
data = {
    'Date': pd.date_range(start='2025-08-01', periods=10, freq='D'),
    'Sales_A': [120, 135, 150, 145, 160, 155, 170, 165, 180, 175],
    'Sales_B': [100, 110, 115, 120, 125, 130, 140, 135, 145, 150]
}

df = pd.DataFrame(data)

# 📝 Assignment: Heatmap Visualization

### **Q1.**

Create a heatmap using Seaborn for weekly performance data. Annotate each cell, customize the color map, and include grid lines.

In [12]:
# Step 1: Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Step 2: Create a NEW dataset
data = {
    'Monday': [12, 18, 25, 30],
    'Tuesday': [15, 22, 28, 35],
    'Wednesday': [20, 26, 33, 40],
    'Thursday': [25, 30, 38, 45],
    'Friday': [28, 35, 42, 50]
}

index = ['Week 1', 'Week 2', 'Week 3', 'Week 4']
df = pd.DataFrame(data, index=index)